### ISSUE TITLE
Wrong format

### ISSUE THREAD

**Issue by WarWolfen** [chikamichi/gitbook-plugin-pdf-styling#10]
error: error with pdf-styling:  Error: invalid book format
    at /tmp/book/node_modules/gitbook-plugin-pdf-styling/lib/post_processing.js:38:13
    at _fulfilled (/tmp/book/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/tmp/book/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/tmp/book/node_modules/q/q.js:749:13)
    at /tmp/book/node_modules/q/q.js:810:14
    at flush (/tmp/book/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9) 
warn: aborting post-processing of pdf 

What can I do to change the books format to get this to work?

**Comment by tsuyoshicho** [comment]
add note

```console
warn: "this.generator" property is deprecated, use "this.output.name" instead 
warn: "navigation" property is deprecated 
warn: "book" property is deprecated, use "this" directly instead 
error: error with pdf-styling:  Error: invalid book format
    at /tmp/book/node_modules/gitbook-plugin-pdf-styling/lib/post_processing.js:38:13
    at _fulfilled (/tmp/book/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/tmp/book/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/tmp/book/node_modules/q/q.js:749:13)
    at /tmp/book/node_modules/q/q.js:810:14
    at flush (/tmp/book/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9) 
warn: aborting post-processing of pdf 
```
